### ISSUE TITLE
Display the timezone offset in the dates/times

### ISSUE THREAD

**Issue by K4LCIFER** [Nutomic/ibis#72] opened 2024-10-19 00:30 UTC
Currently there is no indication of what timezone is used in the displayed dates. This leads to confusion of what time is actually being displayed. For example:
![image](https://github.com/user-attachments/assets/56ee29ba-deae-4014-a933-79bb1b677c3c)
So, for example, following ISO-8601, if it's UTC, it should show `Z`, if it's another timezone, it should show the timezone offset e.g. `-07:00`.

**Comment by Nutomic** [comment] 2024-10-23 09:35
Duplicate of #71

**Closed by Nutomic** 2024-10-23 09:35 UTC

**Comment by K4LCIFER** [comment] 2024-10-24 04:32
> Duplicate of #71

No it's not. This issue is saying that the timezone for the displayed date should be indicated (as it currently isn't).  The other issue is saying that the local timezone shouldn't be used — UTC should be used instead.

**Comment by Nutomic** [comment] 2024-10-25 08:53
It uses the local timezone of the user so there is no need for any indication.

**Comment by K4LCIFER** [comment] 2024-10-26 07:06
> there is no need for any indication.

The entire reason why I opened this issue in the first place was because I couldn't tell what timezone the edits were when I looked at it — I couldn't tell if it was local, or UTC (I had to conduct tests to find out). The fact that that is ambiguous to the reader is rationale enough to warrant the display of the timezone. One shouldn't need to reference the documentation for the service to be able to tell what format the date/time is in. It should be readily apparent in the timestamp itself.

**Comment by K4LCIFER** [comment] 2024-10-29 02:39
> How about displaying the utc time with timestamp as tooltip when you move the mouse over the date?

I think that would be a good feature!

---

Though, I still think it would be a good idea to display the timezone offset even if the time is shown as local time.
